export const films = [
    {
        id: 1,
        image: "/assets/img/films/starwar.jpeg",
        title: "Star Wars: Episode IV - A New Hope",
        year: "1977",
        nation: "USA",
    },
    {
        id: 2,
        image: "/assets/img/films/minion.png",
        title: "Minion",
        year: "2022",
        nation: "USA",
    },
    {
        id: 3,
        image: "/assets/img/films/theGodFather.jpeg",
        title: "The god father",
        year: "1975",
        nation: "USA",
    },
    {
        id: 4,
        image: "/assets/img/films/jeane.jpeg",
        title: "Jeane Dielman",
        year: "1975",
        nation: "Spain",
    },
    {
        id: 5,
        image: "/assets/img/films/raiders.jpeg",
        title: "Raiders of the Lost ark",
        year: "1981",
        nation: "USA",
    },
    {
        id: 6,
        image: "/assets/img/films/blood.jpeg",
        title: "There Will Be Blood",
        year: "1989",
        nation: "England",
    },
    {
        id: 7,
        image: "/assets/img/films/la.jpeg",
        title: "La Donce Vita",
        year: "1960",
        nation: "France",
    },
    {
        id: 8,
        image: "/assets/img/films/samurai.jpeg",
        title: "Seven Samurai",
        year: "1954",
        nation: "Japan",
    },
    {
        id: 9,
        image: "/assets/img/films/love.jpeg",
        title: "In the mood of love",
        year: "2000",
        nation: "Italia",
    },
];
